# Generated by Django 5.1.4 on 2026-05-28 17:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='Short identifier used in API paths and reports.', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emissions_tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('SAP', 'SAP Fuel Procurement'), ('UTILITY', 'Utility Electricity'), ('CONCUR', 'Concur Travel')], help_text='Originating source system.', max_length=20)),
                ('ingestion_timestamp', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when this record was ingested.')),
                ('original_filename', models.CharField(blank=True, default='', help_text='Original filename or API endpoint that produced this record.', max_length=512)),
                ('raw_data', models.JSONField(default=dict, help_text='Original raw payload preserved for audit purposes.')),
                ('transaction_date', models.DateField(blank=True, help_text='Date of the underlying transaction (ISO 8601).', null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('fuel_type', models.CharField(blank=True, default='', max_length=255)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('original_unit', models.CharField(blank=True, default='', max_length=50)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('normalized_unit', models.CharField(blank=True, default='', max_length=50)),
                ('scope', models.IntegerField(blank=True, null=True)),
                ('scope_category', models.IntegerField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by_user_id', models.UUIDField(blank=True, null=True)),
                ('ebeln', models.CharField(blank=True, default='', help_text='SAP Purchase Order number', max_length=20)),
                ('ebelp', models.CharField(blank=True, default='', help_text='SAP Purchase Order item', max_length=10)),
                ('bedat', models.DateField(blank=True, help_text='SAP document date', null=True)),
                ('werks', models.CharField(blank=True, default='', help_text='SAP plant code', max_length=10)),
                ('plant_name', models.CharField(blank=True, default='', max_length=255)),
                ('plant_location', models.CharField(blank=True, default='', max_length=255)),
                ('plant_state', models.CharField(blank=True, default='', max_length=100)),
                ('plant_country', models.CharField(blank=True, default='', max_length=100)),
                ('matnr', models.CharField(blank=True, default='', help_text='SAP material number', max_length=40)),
                ('material_description', models.CharField(blank=True, default='', help_text='SAP TXZ01 field', max_length=255)),
                ('netpr', models.DecimalField(blank=True, decimal_places=6, help_text='SAP net price', max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default='', help_text='SAP WAERS currency code', max_length=10)),
                ('account_number', models.CharField(blank=True, default='', max_length=100)),
                ('meter_id', models.CharField(blank=True, default='', max_length=100)),
                ('service_address', models.CharField(blank=True, default='', max_length=512)),
                ('billing_period_start', models.DateField(blank=True, null=True)),
                ('billing_period_end', models.DateField(blank=True, null=True)),
                ('consumption_kwh', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('reading_type', models.CharField(blank=True, default='', help_text='ACTUAL or ESTIMATED', max_length=20)),
                ('tariff_code', models.CharField(blank=True, default='', max_length=50)),
                ('demand_kw', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('report_id', models.CharField(blank=True, default='', help_text='Concur expense report ID', max_length=100)),
                ('entry_id', models.CharField(blank=True, default='', help_text='Concur expense entry ID', max_length=100)),
                ('expense_type', models.CharField(blank=True, default='', help_text='AIRFARE, HOTEL, GROUND_TRANSPORT_*', max_length=50)),
                ('employee_id', models.CharField(blank=True, default='', max_length=100)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('travel_approval_status', models.CharField(blank=True, default='', help_text='Concur approval status', max_length=50)),
                ('receipt_attached', models.BooleanField(blank=True, null=True)),
                ('origin_airport', models.CharField(blank=True, default='', max_length=10)),
                ('destination_airport', models.CharField(blank=True, default='', max_length=10)),
                ('via_airport', models.CharField(blank=True, default='', max_length=10)),
                ('cabin_class', models.CharField(blank=True, default='', help_text='ECONOMY or BUSINESS', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('hotel_city', models.CharField(blank=True, default='', max_length=255)),
                ('hotel_country', models.CharField(blank=True, default='', max_length=100)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('nights', models.IntegerField(blank=True, null=True)),
                ('ground_fuel_type', models.CharField(blank=True, default='', max_length=100)),
                ('tenant', models.ForeignKey(help_text='The Client_Tenant this record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='emissions.tenant')),
            ],
            options={
                'db_table': 'emissions_emissionrecord',
                'ordering': ['-ingestion_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ANALYST', 'Sustainability Analyst'), ('AUDITOR', 'Auditor'), ('ADMIN', 'Administrator')], default='ANALYST', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, help_text='The Client_Tenant this user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='emissions.tenant')),
            ],
            options={
                'db_table': 'emissions_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('estimated_reading', 'Estimated Reading'), ('missing_receipt', 'Missing Receipt'), ('zero_price', 'Zero Price'), ('blank_quantity', 'Blank Quantity'), ('pending_approval', 'Pending Approval'), ('unknown_airport', 'Unknown Airport'), ('unknown_unit', 'Unknown Unit'), ('potential_duplicate', 'Potential Duplicate')], max_length=50)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_flags', to='emissions.emissionrecord')),
            ],
            options={
                'db_table': 'emissions_dataqualityflag',
                'indexes': [models.Index(fields=['emission_record_id', 'is_resolved'], name='dqf_record_resolved_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('allocated_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit', models.CharField(max_length=50)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_allocations', to='emissions.emissionrecord')),
            ],
            options={
                'db_table': 'emissions_monthlyallocation',
                'ordering': ['year', 'month'],
                'unique_together': {('emission_record', 'year', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant_id'], name='er_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant_id', 'source_system'], name='er_tenant_source_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant_id', 'transaction_date'], name='er_tenant_date_idx'),
        ),
    ]
