# Generated by Django 5.1.4 on 2026-05-28 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emission_record_id', models.UUIDField(db_index=True, help_text='UUID of the EmissionRecord this event relates to.')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='The Client_Tenant this audit event belongs to.')),
                ('event_type', models.CharField(choices=[('CREATE', 'Record Created'), ('UPDATE', 'Field Updated'), ('APPROVE', 'Record Approved'), ('REJECT', 'Record Rejected'), ('LOCK', 'Record Locked for Audit'), ('UNLOCK', 'Record Unlocked')], max_length=20)),
                ('user_id', models.UUIDField(help_text='UUID of the user who triggered this event.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when this event was recorded.')),
                ('field_name', models.CharField(blank=True, default='', help_text='Name of the field that was changed (UPDATE events only).', max_length=100)),
                ('old_value', models.JSONField(blank=True, help_text='Previous field value, JSON-serialized.', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New field value, JSON-serialized.', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context for this event.')),
            ],
            options={
                'db_table': 'audit_auditevent',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant_id'], name='ae_tenant_idx'), models.Index(fields=['tenant_id', 'emission_record_id'], name='ae_tenant_record_idx')],
            },
        ),
    ]
